version: '3'

services:
  jenkins:
    container_name: 'portainer'
    image: 'portainer/portainer'
    volumes:
      - "${LOCAL_DIR}/portainer:/data"
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: -H unix:///var/run/docker.sock
    restart: always

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"
